apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventoryms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: inventoryms
    spec:
      containers:
        - name:  inventoryms-app
          image: inventory/ms
          ports:
            - containerPort: 8070
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m